a=float(input("ingrese su primer valor :"))
b=float(input("ingrese su segundo valor :"))
print("suma:",a+b)
a=float(input("ingrese su primer valor :"))
b=float(input("ingrese su segundo valor :"))
print("resta:",a/b)
a=float(input("ingrese su primer valor :"))
b=float(input("ingrese su segundo valor :"))
print("multi:",a*b)
a=float(input("ingrese su primer valor :"))
b=float(input("ingrese su segundo valor :"))
print("division:",a/b)